package engine

// This engine file is autogenerated by "go generate .". Do not modify.



// ----------------------------------------------------
// Interface Lagoon Generated content
// ----------------------------------------------------
type Lagoon interface {
	
	
	GetEnvironment() Environment	
}
	
func (e *holder) GetEnvironment() Environment{
	return e.env
}	


// ----------------------------------------------------
// Interface Version Generated content
// ----------------------------------------------------
type Version interface {
	
	
	Major() int
	Minor() int
	Micro() int
	AsString() string	
}
	
func (e version) Major() int{
	return e.major
}	

func (e version) Minor() int{
	return e.minor
}	

func (e version) Micro() int{
	return e.micro
}	

func (e version) AsString() string{
	return e.full
}	


// ----------------------------------------------------
// Interface Environment Generated content
// ----------------------------------------------------
type Environment interface {
	
	Labeled
	
	GetVersion() (Version, error)
	GetName() string
	GetDescription() string
	GetBaseLocation() string
	GetLagoonPlatform() LagoonPlatform
	GetProviderDescriptions() ProviderDescriptions
	GetNodeDescriptions() NodeDescriptions
	GetStackDescriptions() StackDescriptions
	GetTaskDescriptions() TaskDescriptions	
}
	
func (e environmentDef) GetVersion() (Version, error){
	return CreateVersion(e.Version)
}	

func (e environmentDef) GetName() string{
	return e.Name
}	

func (e environmentDef) GetDescription() string{
	return e.Description
}	

func (e environmentDef) GetBaseLocation() string{
	return e.BaseLocation
}	

func (e environmentDef) GetLagoonPlatform() LagoonPlatform{
	return e.Lagoon
}	

func (e environmentDef) GetProviderDescriptions() ProviderDescriptions{
	return CreateProviders(e.Providers)
}	

func (e environmentDef) GetNodeDescriptions() NodeDescriptions{
	return CreateNodes(e.Nodes)
}	

func (e environmentDef) GetStackDescriptions() StackDescriptions{
	return CreateStacks(e.Stacks)
}	

func (e environmentDef) GetTaskDescriptions() TaskDescriptions{
	return CreateTasks(e.Tasks)
}	


// ----------------------------------------------------
// Interface LagoonPlatform Generated content
// ----------------------------------------------------
type LagoonPlatform interface {
	
	
	GetVersion() string
	GetRegistry() string
	GetProxy() Proxy	
}
	
func (e platformDef) GetVersion() string{
	return e.Version
}	

func (e platformDef) GetRegistry() string{
	return e.Registry
}	

func (e platformDef) GetProxy() Proxy{
	return e
}	


// ----------------------------------------------------
// Interface Proxy Generated content
// ----------------------------------------------------
type Proxy interface {
	
	
	GetHttp() string
	GetHttps() string
	GetNoProxy() string	
}
	
func (e platformDef) GetHttp() string{
	return e.Proxy.Http
}	

func (e platformDef) GetHttps() string{
	return e.Proxy.Https
}	

func (e platformDef) GetNoProxy() string{
	return e.Proxy.NoProxy
}	


// ----------------------------------------------------
// Interface Labeled Generated content
// ----------------------------------------------------
type Labeled interface {
	
	
	GetLabels() Labels	
}
	
func (e providerDef) GetLabels() Labels{
	return CreateLabels(e.labelsDef.Labels...)
}	

func (e nodeSetDef) GetLabels() Labels{
	return CreateLabels(e.labelsDef.Labels...)
}	

func (e stackDef) GetLabels() Labels{
	return CreateLabels(e.labelsDef.Labels...)
}	

func (e taskDef) GetLabels() Labels{
	return CreateLabels(e.labelsDef.Labels...)
}	

func (e environmentDef) GetLabels() Labels{
	return CreateLabels(e.labelsDef.Labels...)
}	


// ----------------------------------------------------
// Interface Labels Generated content
// ----------------------------------------------------
type Labels interface {
	
	
	Contains(...string) bool
	AsStrings() []string	
}
	

// ----------------------------------------------------
// Interface Parameterized Generated content
// ----------------------------------------------------
type Parameterized interface {
	
	
	GetParameters() Parameters	
}
	
func (e providerDef) GetParameters() Parameters{
	return CreateParameters(e.paramsDef.Params)
}	

func (e nodeSetDef) GetParameters() Parameters{
	return CreateParameters(e.Provider.paramsDef.Params)
}	


// ----------------------------------------------------
// Interface Parameters Generated content
// ----------------------------------------------------
type Parameters interface {
	
	
	AsMap() map[string]string	
}
	

// ----------------------------------------------------
// Interface NodeDescriptions Generated content
// ----------------------------------------------------
type NodeDescriptions interface {
	
	
	Contains(...string) bool
	GetNode(string) (NodeDescription, bool)	
}
	

// ----------------------------------------------------
// Interface NodeDescription Generated content
// ----------------------------------------------------
type NodeDescription interface {
	
	Labeled
	
	GetInstances() int
	GetProviderName() ProviderName	
}
	
func (e nodeSetDef) GetInstances() int{
	return e.Instances
}	

func (e nodeSetDef) GetProviderName() ProviderName{
	return e
}	


// ----------------------------------------------------
// Interface ProviderDescriptions Generated content
// ----------------------------------------------------
type ProviderDescriptions interface {
	
	
	Contains(...string) bool
	GetProvider(string) (ProviderDescription, bool)	
}
	

// ----------------------------------------------------
// Interface ProviderDescription Generated content
// ----------------------------------------------------
type ProviderDescription interface {
	
	Labeled
	Parameterized
		
}
	

// ----------------------------------------------------
// Interface StackDescriptions Generated content
// ----------------------------------------------------
type StackDescriptions interface {
	
	
	Contains(...string) bool
	GetStack(string) (StackDescription, bool)	
}
	

// ----------------------------------------------------
// Interface StackDescription Generated content
// ----------------------------------------------------
type StackDescription interface {
	
	Labeled
	
	GetRepository() string
	GetVersion() string	
}
	
func (e stackDef) GetRepository() string{
	return e.Repository
}	

func (e stackDef) GetVersion() string{
	return e.Version
}	


// ----------------------------------------------------
// Interface TaskDescriptions Generated content
// ----------------------------------------------------
type TaskDescriptions interface {
	
	
	Contains(...string) bool
	GetTask(string) (TaskDescription, bool)	
}
	

// ----------------------------------------------------
// Interface TaskDescription Generated content
// ----------------------------------------------------
type TaskDescription interface {
	
	Labeled
	
	GetPlaybook() string
	GetCron() string	
}
	
func (e taskDef) GetPlaybook() string{
	return e.Playbook
}	

func (e taskDef) GetCron() string{
	return e.Cron
}	


// ----------------------------------------------------
// Interface ProviderName Generated content
// ----------------------------------------------------
type ProviderName interface {
	
	Parameterized
	
	GetName() string	
}
	
func (e nodeSetDef) GetName() string{
	return e.Provider.Name
}	

