// Package tmodel is a collection of interfaces representing a Read Only environment.
//
//*****************************************************************************
//
// All the package content is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************
//
package tmodel
