package tmodel

import (
	"github.com/ekara-platform/model"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// TBase is a read only base location
type TBase interface {
	//URL returns the url where the base refers
	URL() TURL
}

// ----------------------------------------------------
// Implementation(s) of TBase
// ----------------------------------------------------

//TBaseOnBaseHolder is the struct containing the Base in order to implement TBase
type TBaseOnBaseHolder struct {
	h model.Base
}

//CreateTBaseForBase returns an holder of Base implementing TBase
func CreateTBaseForBase(o model.Base) TBaseOnBaseHolder {
	return TBaseOnBaseHolder{
		h: o,
	}
}

//URL returns the url where the base refers
func (r TBaseOnBaseHolder) URL() TURL {
	return CreateTURLForEkUrl(r.h.Url)
}
