package tmodel

import (
	"github.com/ekara-platform/model"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// TProxy is a read only proxy configuration
type TProxy interface {
	//HTTP returns the proxy http definition
	HTTP() string
	//HTTPS returns the proxy https definition
	HTTPS() string
	//NoProxy returns the no proxy definition
	NoProxy() string
}

// ----------------------------------------------------
// Implementation(s) of TProxy
// ----------------------------------------------------

//TProxyOnProxyHolder is the struct containing the Proxy in order to implement TProxy
type TProxyOnProxyHolder struct {
	h model.Proxy
}

//CreateTProxyForProxy returns an holder of Proxy implementing TProxy
func CreateTProxyForProxy(o model.Proxy) TProxyOnProxyHolder {
	return TProxyOnProxyHolder{
		h: o,
	}
}

//HTTP returns the proxy http definition
func (r TProxyOnProxyHolder) HTTP() string {
	return r.h.Http
}

//HTTPS returns the proxy https definition
func (r TProxyOnProxyHolder) HTTPS() string {
	return r.h.Https
}

//NoProxy returns the no proxy definition
func (r TProxyOnProxyHolder) NoProxy() string {
	return r.h.NoProxy
}
