package engine

import(
	"github.com/ekara-platform/model"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// TProxy is a read only proxy configuration
// ----------------------------------------------------
type TProxy interface {
    //Http returns the proxy http definition
    Http() string
    //Https returns the proxy https definition
    Https() string
    //NoProxy returns the no proxy definition
    NoProxy() string
	
}

// ----------------------------------------------------
// Implementation(s) of TProxy  
// ----------------------------------------------------

//TProxyOnProxyHolder is the struct containing the Proxy in otder to implement TProxy  
type TProxyOnProxyHolder struct {
	h 	model.Proxy
}

//CreateTProxyForProxy returns a holder implementing TProxy
func CreateTProxyForProxy(o model.Proxy) TProxyOnProxyHolder {
	return TProxyOnProxyHolder{
		h: o,
	}
}

//Http returns the proxy http definition
func (r TProxyOnProxyHolder) Http() string{
	return r.h.Http
}

//Https returns the proxy https definition
func (r TProxyOnProxyHolder) Https() string{
	return r.h.Https
}

//NoProxy returns the no proxy definition
func (r TProxyOnProxyHolder) NoProxy() string{
	return r.h.NoProxy
}

