package engine

import(
	"github.com/ekara-platform/model"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// TProviderRef is a read only reference on a provider
// ----------------------------------------------------
type TProviderRef interface {
    //Provider returns the provider wherein the node should be deployed
    Provider() (TProvider, error)
	
}

// ----------------------------------------------------
// Implementation(s) of TProviderRef  
// ----------------------------------------------------

//TProviderRefOnProviderRefHolder is the struct containing the ProviderRef in order to implement TProviderRef  
type TProviderRefOnProviderRefHolder struct {
	h 	model.ProviderRef
}

//CreateTProviderRefForProviderRef returns an holder of ProviderRef implementing TProviderRef
func CreateTProviderRefForProviderRef(o model.ProviderRef) TProviderRefOnProviderRefHolder {
	return TProviderRefOnProviderRefHolder{
		h: o,
	}
}

//Provider returns the provider wherein the node should be deployed
func (r TProviderRefOnProviderRefHolder) Provider() (TProvider, error){
	    v, err := r.h.Resolve()
    return CreateTProviderForProvider(v), err
}

