package engine

import (
	"github.com/ekara-platform/model"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// TStackRef is a read only reference on a stack
type TStackRef interface {
	//Stack returns the stack corresponding to the ref
	Stack() (TStack, error)
}

// ----------------------------------------------------
// Implementation(s) of TStackRef
// ----------------------------------------------------

//TStackRefOnStackRefHolder is the struct containing the StackRef in order to implement TStackRef
type TStackRefOnStackRefHolder struct {
	h model.StackRef
}

//CreateTStackRefForStackRef returns an holder of StackRef implementing TStackRef
func CreateTStackRefForStackRef(o model.StackRef) TStackRefOnStackRefHolder {
	return TStackRefOnStackRefHolder{
		h: o,
	}
}

//Stack returns the stack corresponding to the ref
func (r TStackRefOnStackRefHolder) Stack() (TStack, error) {
	v, err := r.h.Resolve()
	return CreateTStackForStack(v), err
}
