package engine

import(
	"github.com/ekara-platform/model"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// TTaskRef is a read only reference on a task
// ----------------------------------------------------
type TTaskRef interface {
    //Task returns the task corresponding to the ref
    Task() (TTask, error)
	
}

// ----------------------------------------------------
// Implementation(s) of TTaskRef  
// ----------------------------------------------------

//TTaskRefOnTaskRefHolder is the struct containing the TaskRef in otder to implement TTaskRef  
type TTaskRefOnTaskRefHolder struct {
	h 	model.TaskRef
}

//CreateTTaskRefForTaskRef returns a holder implementing TTaskRef
func CreateTTaskRefForTaskRef(o model.TaskRef) TTaskRefOnTaskRefHolder {
	return TTaskRefOnTaskRefHolder{
		h: o,
	}
}

//Task returns the task corresponding to the ref
func (r TTaskRefOnTaskRefHolder) Task() (TTask, error){
	    v, err := r.h.Resolve()
    return CreateTTaskForTask(v), err
}

