package engine

import(
	"github.com/ekara-platform/model"
)

//*****************************************************************************
//
// This file is autogenerated by "go generate .". Do not modify.
//
//*****************************************************************************

// ----------------------------------------------------
// TUrl is a read only ekara url
// ----------------------------------------------------
type TUrl interface {
    //String returns the string representation of the whole url
    String() string
    //Scheme returns the url scheme
    Scheme() string
    //Path returns the url path
    Path() string
    //AsFilePath returns the path converted as a file path
    AsFilePath() string
    //Host returns the url host
    Host() string
	
}

// ----------------------------------------------------
// Implementation(s) of TUrl  
// ----------------------------------------------------

//TUrlOnEkUrlHolder is the struct containing the EkUrl in otder to implement TUrl  
type TUrlOnEkUrlHolder struct {
	h 	model.EkUrl
}

//CreateTUrlForEkUrl returns a holder implementing TUrl
func CreateTUrlForEkUrl(o model.EkUrl) TUrlOnEkUrlHolder {
	return TUrlOnEkUrlHolder{
		h: o,
	}
}

//String returns the string representation of the whole url
func (r TUrlOnEkUrlHolder) String() string{
	return r.h.String()
}

//Scheme returns the url scheme
func (r TUrlOnEkUrlHolder) Scheme() string{
	return r.h.Scheme()
}

//Path returns the url path
func (r TUrlOnEkUrlHolder) Path() string{
	return r.h.Path()
}

//AsFilePath returns the path converted as a file path
func (r TUrlOnEkUrlHolder) AsFilePath() string{
	return r.h.AsFilePath()
}

//Host returns the url host
func (r TUrlOnEkUrlHolder) Host() string{
	return r.h.Host()
}

